In [1]:
import numpy as np

Scalar

In [3]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

Vector

In [4]:
x = np.array([42, 3, 5, 6])
print(x.shape)
x.ndim

(4,)


1

Matrix

In [8]:
x = np.array([
  [42, 3, 5, 6,1 ,2],
  [2, 31, 25, 36, 1 ,2]
])
print(x.shape)
x.ndim


(2, 6)


2

Tensor

In [7]:
x = np.array([
  [
    [42, 3, 5, 6, 1,2],
    [2, 31, 25, 36, 2 ,3]
  ],
  [
    [42, 3, 5, 6, 1,2],
    [2, 31, 25, 36, 2 ,3]
  ],
  [
    [42, 3, 5, 6, 1,2],
    [2, 31, 25, 36, 2 ,3]
  ]
])
print(x.shape)
x.ndim


(3, 2, 6)


3

### Reshape

In [9]:
x = np.array([
  [0,1],
  [2, 3],
  [4, 5],
  [6, 7],
  [8, 9],
  [10, 11]
])

x.shape

(6, 2)

In [11]:
x.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [12]:
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [13]:
x.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [15]:
# matriz traspuesta
x.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [16]:
np.transpose(x)

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])